# Generated by Django 5.1.15 on 2026-09-29 02:48

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BoundVolume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('call_number', models.CharField(max_length=64, unique=True, verbose_name='合订本索取号')),
                ('barcode', models.CharField(max_length=40, unique=True, verbose_name='合订本条码')),
                ('title_display', models.CharField(help_text='如 第55卷合订本(2023-2024)', max_length=255, verbose_name='册标识')),
                ('location', models.CharField(max_length=128, verbose_name='馆藏位置')),
                ('bound_at', models.DateTimeField(blank=True, null=True, verbose_name='装订时间')),
                ('is_bound', models.BooleanField(default=True, verbose_name='是否在订')),
                ('note', models.CharField(blank=True, default='', max_length=255, verbose_name='备注')),
            ],
            options={
                'verbose_name': '装订册',
                'verbose_name_plural': '装订册',
                'ordering': ('call_number',),
            },
        ),
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('volume', models.PositiveIntegerField(blank=True, null=True, verbose_name='卷')),
                ('issue_no', models.PositiveIntegerField(blank=True, null=True, verbose_name='期号')),
                ('pub_year', models.PositiveIntegerField(verbose_name='发行年')),
                ('pub_month', models.PositiveIntegerField(blank=True, null=True, verbose_name='发行月')),
                ('issue_type', models.CharField(choices=[('normal', '普通期'), ('combined', '合刊期'), ('ceased', '停刊月份')], default='normal', max_length=10, verbose_name='类型')),
                ('combined_group', models.CharField(blank=True, default='', help_text='同一合刊组的期入藏到同一实体', max_length=40, verbose_name='合刊组标识')),
                ('note', models.CharField(blank=True, default='', max_length=255, verbose_name='说明')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='登记时间')),
            ],
            options={
                'verbose_name': '期号（发行记录）',
                'verbose_name_plural': '期号（发行记录）',
                'ordering': ('serial', 'volume', 'issue_no', 'pub_year', 'pub_month'),
            },
        ),
        migrations.CreateModel(
            name='Serial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='刊名')),
                ('issn', models.CharField(blank=True, default='', max_length=9, verbose_name='ISSN')),
                ('publisher', models.CharField(blank=True, default='', max_length=255, verbose_name='出版者')),
                ('note', models.TextField(blank=True, default='', verbose_name='备注')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='登记时间')),
            ],
            options={
                'verbose_name': '连续出版物',
                'verbose_name_plural': '连续出版物',
                'ordering': ('title',),
            },
        ),
        migrations.CreateModel(
            name='Piece',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barcode', models.CharField(max_length=40, unique=True, verbose_name='条码')),
                ('call_number', models.CharField(max_length=64, verbose_name='索取号')),
                ('location', models.CharField(max_length=128, verbose_name='自身位置')),
                ('location_before_binding', models.CharField(blank=True, default='', max_length=128, verbose_name='装订前位置')),
                ('bind_order', models.PositiveIntegerField(default=0, verbose_name='装订顺序')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='入藏时间')),
                ('bound_volume', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pieces', to='serials.boundvolume', verbose_name='所在装订册')),
            ],
            options={
                'verbose_name': '实体分册',
                'verbose_name_plural': '实体分册',
                'ordering': ('serial', 'call_number', 'bind_order', 'barcode'),
            },
        ),
        migrations.CreateModel(
            name='BindingEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('bind', '装订'), ('unbind', '拆订')], max_length=6, verbose_name='操作')),
                ('location_from', models.CharField(blank=True, max_length=128, verbose_name='操作前位置')),
                ('location_to', models.CharField(blank=True, max_length=128, verbose_name='操作后位置')),
                ('operator', models.CharField(blank=True, default='', max_length=64, verbose_name='操作员')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='时间')),
                ('bound_volume', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='serials.boundvolume', verbose_name='装订册')),
                ('piece', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='binding_events', to='serials.piece', verbose_name='实体分册')),
            ],
            options={
                'verbose_name': '装订流水',
                'verbose_name_plural': '装订流水',
                'ordering': ('-created_at', '-id'),
            },
        ),
        migrations.CreateModel(
            name='PieceIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='册内顺序')),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='piece_issues', to='serials.issue', verbose_name='期号')),
                ('piece', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='piece_issues', to='serials.piece', verbose_name='实体分册')),
            ],
            options={
                'verbose_name': '实体-期号关联',
                'verbose_name_plural': '实体-期号关联',
                'ordering': ('order', 'issue__volume', 'issue__issue_no'),
            },
        ),
        migrations.AddField(
            model_name='piece',
            name='issues',
            field=models.ManyToManyField(related_name='pieces', through='serials.PieceIssue', to='serials.issue', verbose_name='关联期号'),
        ),
        migrations.AddField(
            model_name='piece',
            name='serial',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pieces', to='serials.serial', verbose_name='期刊'),
        ),
        migrations.AddField(
            model_name='issue',
            name='serial',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='serials.serial', verbose_name='期刊'),
        ),
        migrations.AddConstraint(
            model_name='pieceissue',
            constraint=models.UniqueConstraint(fields=('issue',), name='uniq_one_piece_per_issue'),
        ),
        migrations.AddConstraint(
            model_name='pieceissue',
            constraint=models.UniqueConstraint(fields=('piece', 'issue'), name='uniq_piece_issue_pair'),
        ),
        migrations.AddIndex(
            model_name='issue',
            index=models.Index(fields=['serial', 'volume'], name='serials_iss_serial__4c6be8_idx'),
        ),
        migrations.AddIndex(
            model_name='issue',
            index=models.Index(fields=['pub_year', 'pub_month'], name='serials_iss_pub_yea_34d37b_idx'),
        ),
        migrations.AddConstraint(
            model_name='issue',
            constraint=models.UniqueConstraint(fields=('serial', 'volume', 'issue_no'), name='uniq_issue_citation'),
        ),
        migrations.AddConstraint(
            model_name='issue',
            constraint=models.CheckConstraint(condition=models.Q(('combined_group', ''), ('issue_type', 'combined'), _negated=True), name='check_combined_has_group'),
        ),
        migrations.AddConstraint(
            model_name='issue',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('issue_type__in', ['normal', 'combined']), models.Q(('volume__isnull', True), _negated=True), models.Q(('issue_no__isnull', True), _negated=True)), models.Q(('issue_type', 'ceased'), ('volume__isnull', True), ('issue_no__isnull', True)), _connector='OR'), name='check_issue_numbering_by_type'),
        ),
        migrations.AddConstraint(
            model_name='issue',
            constraint=models.CheckConstraint(condition=models.Q(('pub_month__isnull', True), models.Q(('pub_month__gte', 1), ('pub_month__lte', 12)), _connector='OR'), name='check_pub_month_range'),
        ),
    ]
